 (load "path.clp")
 (bind ?c (str-cat ?*chlpath* "/clip_files/rel.clp"))
 (load* ?c)
 (load-facts "user_intrachunk_rel_tmp.dat")
 (load-facts "user_interchunk_rel_tmp.dat")
 (load-facts "user_discourse_rel_tmp.dat")
 (assert (user_intra_chunk_rel-ids))
 (assert (user_discourse_rel-ids))
 (agenda)
 (run)
 (save-facts "user_intrachunk_rel.dat" local user_intra_chunk_rel-ids)
 (save-facts "user_interchunk_rel.dat" local user_inter_chunk_rel-ids)
 (save-facts "user_discourse_rel.dat" local user_discourse_rel-ids)
 (clear)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
 (defmodule MAIN (export ?ALL))
 (load-facts "user_chunk_and_vib_info.dat")
 (load-facts "user_intrachunk_rel.dat")
 (load-facts "user_interchunk_rel.dat")
 (load-facts "user_discourse_rel.dat")
 (load-facts "user_cat_info.dat")
 (load-facts "user_definiteness_info.dat")
 (load-facts "user_gnp_info.dat")
 (load-facts "user_lemma_info.dat")
 (load-facts "prep_insertion_based_on_verb.dat")
 (load-facts "default_prep_insertion_based_on_rel.dat")
 (load "path.clp")
 (defmodule PREP_DISAMBIGUATION_MODULE (export ?ALL)
                       (import MAIN ?ALL))
 (set-current-module PREP_DISAMBIGUATION_MODULE)
 (bind ?c (str-cat ?*chlpath* "/clip_files/prep_disambiguation_rules.clp"))
 (bind ?p (str-cat ?*chlpath* "/clip_files/prep_prov_rules/"))
 (bind ?w (str-cat ?*chlpath* "/clip_files/prep_rules/"))
 (defglobal ?*prep_prov_path* = ?p)
 (defglobal ?*prep_path* = ?w)
 (load* ?c)
 (open "prep_debug_file.dat" prep_fp "a")
 (focus PREP_DISAMBIGUATION_MODULE)
 (watch rules)
 (watch facts)
 (agenda)
 (run)
 (focus PREP_DISAMBIGUATION_MODULE)
 (undefrule *)
 (defrule retract_cntrl_fact
 (declare (salience -9999))
 ?f0<-(file_loaded ?id)
 =>
 (retract ?f0)
 )
 (run)
 (focus PREP_DISAMBIGUATION_MODULE)
 (save-facts "prep_insertion.dat" local)
 (clear)
 (exit)
