#!/usr/bin/env bash
MY_PATH=$PWD
#echo $MY_PATH
BASEDIR=$(dirname "$0")
#echo $BASEDIR
uconv -c -f UTF-8 -t x-iscii-de $1  > $1_iscii
sed 's/ï.//g' $1_iscii > $1_iscii1
#$PWD/$BASEDIR/ir_no@ < $1_iscii1  | sed -e 's/OY/oY/g'
$BASEDIR/ir_no@ < $1_iscii1  | sed -e 's/OY/oY/g'
rm $1_isc*
#ir_no@ removes @ in the iscii o/p
#ir stores the @ info
